### ISSUE TITLE
Seems it's broken

### ISSUE THREAD

**Issue by luizbills** [joelnet/mojiscript-cli#5]
I cloned the mojiscript repo, the tests passed but I can't commit the changes. The terminal emits:

```
$ node -v
v14.2.0
$ npm run build

> mojiscript@0.13.10 build /workspace/MojiScript
> moji build .

internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspace/MojiScript/node_modules/mojiscript/console/log' imported from /workspace/MojiScript/node_modules/mojiscript-cli/src/index.mjs
Did you mean to import mojiscript/console/log.js?
    at finalizeResolution (internal/modules/esm/resolve.js:277:11)
    at packageResolve (internal/modules/esm/resolve.js:608:14)
    at moduleResolve (internal/modules/esm/resolve.js:655:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:748:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
[...]
```

Also tested with Node LTS (v12.16.3)

**Comment by joelnet** [comment]
I have had too many problems with the mjs extension. I think this problem happens after node 12. I'm planning on redoing all of it with commonjs and no mjs.

**Comment by luizbills** [comment]
I guess it will be the best solution
